### PR TITLE
Team member 4

### PR DESCRIPTION
**Pull request by Trictonicmp**
#### In this PR I:

- [x] Added Source class
- [x] Added method ```add_item``` to Source class
- [x] Added tests for Source class

### CODE REVIEW

**Review by marilirulita — APPROVED** [review]
## Good job this is approved! 💯

**Review by marilirulita — APPROVED** [review]
### 💯  This is Approved, keep doing the good job!

**Review by joshuaoivie — APPROVED** [review]
Great Job @Trictonicmp! Way to go!

**Comment by joshuaoivie** [comment]
> ### 💯 This is Approved, keep doing the good job!

[😂](https://emojipedia.org/face-with-tears-of-joy/) Sorry I didn't know you were approving too!

**Pull request merged**
